#!/bin/bash
#
#	/etc/rc.d/init.d/cryptoclient
#
# chkconfig: 2345 80 80
# pidfile: /var/run/cryptoclient.pid

# Source function library.
. /etc/init.d/functions

start() {
        action "Starting cryptoclient: " \
                /opt/rocks/bin/cryptoclient start
        return $?
}	

stop() {
	action "Shutting down cryptoclient: "
		/opt/rocks/bin/cryptoclient stop
	return $?
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
	status cryptoclient
	;;
    restart)
    	stop
	start
	;;
    *)
	echo "Usage: cryptoclient {start|stop|status|restart]"
	exit 1
	;;
esac
exit $?
