#!/bin/bash
#
#	/etc/rc.d/init.d/acctman-fe-server
#
# chkconfig: 2345 80 80
# pidfile: /var/run/cryptoserver.pid

# Source function library.
. /etc/init.d/functions

start() {
        action "Starting cryptoserver: " \
                /opt/rocks/bin/cryptoserver start
        return $?
}	

stop() {
	action "Shutting down cryptoserver: "
		/opt/rocks/bin/cryptoserver stop
	return $?
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
	status cryptoserver
	;;
    restart)
    	stop
	start
	;;
    *)
	echo "Usage: cryptoserver {start|stop|status|restart]"
	exit 1
	;;
esac
exit $?
